version: "3.8"
services:
  price-checker:
    build: .
    container_name: price-checker
    env_file:
      - .env
    volumes:
      - ${PRICE_CHECKER__DB_DIR}:${PRICE_CHECKER__DB_DIR}
    restart: unless-stopped
