CREATE TABLE "price-checker_check" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price-checker_check_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"itemId" integer NOT NULL,
	"price" numeric(10, 2),
	"availableInStoresCount" integer DEFAULT 0 NOT NULL,
	"checkedAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price-checker_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price-checker_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" text NOT NULL,
	"title" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "price-checker_item_url_unique" UNIQUE("url")
);
--> statement-breakpoint
ALTER TABLE "price-checker_check" ADD CONSTRAINT "price-checker_check_itemId_price-checker_item_id_fk" FOREIGN KEY ("itemId") REFERENCES "public"."price-checker_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "check_item_id_idx" ON "price-checker_check" USING btree ("itemId");--> statement-breakpoint
CREATE INDEX "item_url_idx" ON "price-checker_item" USING btree ("url");